FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=securepass123
ENV GENERIC_TIMEZONE=Europe/Kyiv
ENV N8N_RUNNERS_ENABLED=true

VOLUME /home/node/.n8n

CMD ["n8n"]
