services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepass123
      - WEBHOOK_URL=https://ec2.whivex.store
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Europe/Kyiv
      - N8N_RUNNERS_ENABLED=true
      - N8N_GIT_SYNC_ACTIVE=true
      - N8N_GIT_SYNC_REPOSITORY=https://github.com/Subx1s0o/n8n.git
      - N8N_GIT_SYNC_BRANCH=main
      - N8N_GIT_SYNC_USERNAME=Subx1s0o
      - N8N_GIT_SYNC_PASSWORD=${N8N_GIT_SYNC_PASSWORD}
      - N8N_GIT_SYNC_SYNC_INTERVAL=60
      - N8N_GIT_SYNC_AUTOCOMMIT=true
      - N8N_GIT_SYNC_PUSH_ON_CHANGES=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
