services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-viab.onrender.com
      - key: N8N_PORT
        value: 5678           
      - key: N8N_PROTOCOL
        value: http
      - key: N8N_HOST
        value: 0.0.0.0
